CREATE TABLE CUSTOMIZABLE
(
    IMAGEN VARCHAR(255) PRIMARY KEY
);

CREATE TABLE FOTO_PERFIL
(
    F_PERFIL VARCHAR(255) PRIMARY KEY ,
    FOREIGN KEY (F_PERFIL) REFERENCES CUSTOMIZABLE(IMAGEN)
);

CREATE TABLE FONDO_CARTA
(
    F_CARTA VARCHAR(255) PRIMARY KEY ,
    FOREIGN KEY (F_CARTA) REFERENCES CUSTOMIZABLE(IMAGEN)
);

CREATE TABLE FONDO_TAPETE
(
    F_TAPETE VARCHAR(255) PRIMARY KEY ,
    FOREIGN KEY (F_TAPETE) REFERENCES CUSTOMIZABLE(IMAGEN)
);

CREATE TABLE USUARIO
(
    USERNAME VARCHAR(255) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    COPAS INT DEFAULT 0,
    F_PERFIL VARCHAR(255),
    F_TAPETE VARCHAR(255),
    F_CARTA VARCHAR(255),
    FOREIGN KEY (F_PERFIL) REFERENCES FOTO_PERFIL(F_PERFIL),
    FOREIGN KEY (F_TAPETE) REFERENCES FONDO_TAPETE(F_TAPETE),
    FOREIGN KEY (F_CARTA) REFERENCES FONDO_CARTA(F_CARTA)
);

CREATE TABLE AMIGO
(
    USUARIO VARCHAR(20),
    AMIGO VARCHAR(20),
    CONSTRAINT AMIGO_PK PRIMARY KEY(USUARIO,AMIGO),
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(USERNAME),
    FOREIGN KEY (AMIGO) REFERENCES USUARIO(USERNAME)
);

CREATE TABLE CARTA
(
    CARTA VARCHAR(2) PRIMARY KEY,
    PUNTUACION INT
);
-- FALTA POR RELLENAR
CREATE TABLE PARTIDA
(
    NOMBRE VARCHAR(255) PRIMARY KEY,
    ESTADO INT,
    TIPO INT,
    FECHA DATE
);

CREATE TABLE PERTENECE
(
    JUGADOR VARCHAR(255),
    PARTIDA VARCHAR(255),
    EQUIPO INT,
    C1 VARCHAR(2),
    C2 VARCHAR(2),
    C3 VARCHAR(2),
    C4 VARCHAR(2),
    C5 VARCHAR(2),
    C6 VARCHAR(2),
    PRIMARY KEY (JUGADOR,PARTIDA),
    FOREIGN KEY (C1) REFERENCES CARTA(CARTA),
    FOREIGN KEY (C2) REFERENCES CARTA(CARTA),
    FOREIGN KEY (C3) REFERENCES CARTA(CARTA),
    FOREIGN KEY (C4) REFERENCES CARTA(CARTA),
    FOREIGN KEY (C5) REFERENCES CARTA(CARTA),
    FOREIGN KEY (C6) REFERENCES CARTA(CARTA),
    FOREIGN KEY (JUGADOR) REFERENCES USUARIO(USERNAME),
    FOREIGN KEY (PARTIDA) REFERENCES PARTIDA(NOMBRE)
);

CREATE TABLE JUEGA
(
    JUGADOR VARCHAR(255),
    NRONDA INT,
    PARTIDA VARCHAR(255),
    CARTA VARCHAR(2),
    PRIMARY KEY (JUGADOR,PARTIDA,CARTA),
    FOREIGN KEY (CARTA) REFERENCES CARTA(CARTA),
    FOREIGN KEY (JUGADOR) REFERENCES USUARIO(USERNAME),
    FOREIGN KEY (PARTIDA) REFERENCES PARTIDA(NOMBRE)
);

CREATE TABLE TORNEO
(
    NOMBRE VARCHAR(255) PRIMARY KEY,
    TIPO INT,
    NPARTICIPANTES INT
);

CREATE TABLE TORNEO_PUBLICO
(
    NOMBRE VARCHAR(255) PRIMARY KEY,
    FOREIGN KEY (NOMBRE) REFERENCES TORNEO(NOMBRE)
);

CREATE TABLE TORNEO_PRIVADO
(
    NOMBRE VARCHAR(255) PRIMARY KEY,
    CONTRASENYA VARCHAR(255) NOT NULL,
    FOREIGN KEY (NOMBRE) REFERENCES TORNEO(NOMBRE)
);

CREATE TABLE PARTICIPANTES_TORNEO
(
    TORNEO VARCHAR(255),
    PARTIDA VARCHAR(255),
    CONSTRAINT PT_PK PRIMARY KEY (TORNEO,PARTIDA),
    FOREIGN KEY (TORNEO) REFERENCES TORNEO(NOMBRE),
    FOREIGN KEY (PARTIDA) REFERENCES PARTIDA(NOMBRE)


);
CREATE TABLE PARTIDAS_TORNEO
(
    TORNEO VARCHAR(255),
    PARTIDA VARCHAR(255),
    CONSTRAINT PARTIDASTORNEO_PK PRIMARY KEY(TORNEO,PARTIDA),
    FOREIGN KEY (TORNEO) REFERENCES TORNEO(NOMBRE),
    FOREIGN KEY (PARTIDA) REFERENCES PARTIDA(NOMBRE)

);

CREATE TABLE FORO
(
    PARTIDA VARCHAR(255),
    MENSAJE VARCHAR(255),
    CONSTRAINT FORO_PK PRIMARY KEY (PARTIDA,MENSAJE),
    FOREIGN KEY (PARTIDA) REFERENCES PARTIDA(NOMBRE)
);

CREATE TABLE CHAT
(
    IDCHAT SERIAL PRIMARY KEY,
    MENSAJE VARCHAR(255),
    USUARIO VARCHAR(255),
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(USERNAME)
);

CREATE TABLE PERTENCE_CHAT
(
    USUARIO VARCHAR(255),
    IDCHAT INT,
    CONSTRAINT PC_PK PRIMARY KEY (USUARIO,IDCHAT),
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(USERNAME)
);